package org.dedeler.template.exception;

public enum ErrorCode {

	UNKNOWN_ERROR,
	INVALID_CREDENTIALS,
	INVALID_PASSWORD,
	INVALID_USERNAME,
	ACCESS_DENIED,
	USER_NOT_ACTIVATED,
	DAO_LAYER_EXCEPTION

}
